# Generated by Django 3.2.3 on 2021-05-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(choices=[('Burundi', 'Burundi'), ('Kenya', 'Kenya'), ('Rwanda', 'Rwanda'), ('South Sudan', 'South Sudan'), ('Tanzania', 'Tanzania'), ('Uganda', 'Uganda')], default='Burundi', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('iucea_membership', models.CharField(choices=[('full member', 'full member'), ('associate', 'associate'), ('not member', 'not member')], default='full member', max_length=100)),
                ('type_of_establishment', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='public', max_length=100)),
                ('level_of_progression', models.CharField(choices=[('chartered', 'chartered'), ('provisional', 'provisional'), ('letter_of_intent', 'letter_of_intent')], default='chartered', max_length=100)),
                ('website', models.URLField(default='', max_length=140)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='academic_programs_information_system.country')),
            ],
            options={
                'verbose_name_plural': 'universities',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('program_level', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Post Graduate Diploma', 'Post Graduate Diploma'), ('Doctorate', 'Doctorate')], default='Bachelors', max_length=100)),
                ('program_offering', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Weekend', 'Weekend'), ('Online', 'Online')], default='Full Time', max_length=100)),
                ('thematic_area', models.CharField(choices=[('Science', 'Science'), ('Engineering', 'Engineering'), ('Business', 'Business')], default='Science', max_length=100)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academic_programs_information_system.country')),
                ('university', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academic_programs_information_system.university')),
            ],
        ),
    ]
